package com.iamxpp.isaver.transfer

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class TargetNameResolverTest {
    private val resolver = TargetNameResolver(maxAttempts = 100)

    @Test fun `attempts preserve the explicit stem and extension boundary`() {
        val cases = mapOf(
            OutputNameDraft.fromDisplayName("a.txt") to "a (1).txt",
            OutputNameDraft.fromDisplayName("README") to "README (1)",
            OutputNameDraft.fromDisplayName("archive.tar.gz") to "archive.tar (1).gz",
            OutputNameDraft(stem = "archive", extension = "tar.gz") to "archive (1).tar.gz",
            OutputNameDraft.fromDisplayName(".env") to ".env (1)",
            OutputNameDraft.fromDisplayName(".config.json") to ".config (1).json",
            OutputNameDraft.fromDisplayName("name.") to "name. (1)",
            OutputNameDraft.fromDisplayName("中文 😀 ' \n.txt") to "中文 😀 ' \n (1).txt",
        )
        cases.forEach { (draft, expected) ->
            assertEquals(draft.toEntryName().getOrThrow(), resolver.resolve(draft, 0).getOrThrow())
            assertEquals(expected, resolver.resolve(draft, 1).getOrThrow().value)
        }
    }

    @Test fun `invalid originals attempts and generated byte overflow are typed failures`() {
        listOf("", " ", ".", "..", "a/b", "a\u0000b").forEach { stem ->
            assertTrue(
                resolver.resolve(OutputNameDraft(stem, ""), 0).exceptionOrNull() is TargetNameException.InvalidName,
            )
        }
        assertTrue(
            resolver.resolve(OutputNameDraft("report", ".pdf"), 0).exceptionOrNull() is TargetNameException.InvalidName,
        )
        assertTrue(resolver.resolve(OutputNameDraft("a", ""), -1).exceptionOrNull() is TargetNameException.InvalidAttempt)
        assertTrue(resolver.resolve(OutputNameDraft("a", ""), 100).exceptionOrNull() is TargetNameException.AttemptsExhausted)
        val draft = OutputNameDraft("你".repeat(83), "txt")
        assertTrue(resolver.resolve(draft, 1).exceptionOrNull() is TargetNameException.NameTooLong)
    }

    @Test fun `rejects malformed unicode surrogates but preserves a valid emoji pair`() {
        assertTrue(
            resolver.resolve(OutputNameDraft("bad-\uD83D", "txt"), 0).exceptionOrNull() is TargetNameException.InvalidName,
        )
        assertTrue(
            resolver.resolve(OutputNameDraft("bad-\uDE00", "txt"), 0).exceptionOrNull() is TargetNameException.InvalidName,
        )
        assertEquals(
            "ok-😀 (1).txt",
            resolver.resolve(OutputNameDraft("ok-😀", "txt"), 1).getOrThrow().value,
        )
    }
}
