package com.iamxpp.isaver.transfer

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class TargetNameResolverTest {
    private val resolver = TargetNameResolver(maxAttempts = 100)

    @Test fun `attempt zero preserves original and later attempts preserve extension rules`() {
        val cases = mapOf(
            "a.txt" to "a (1).txt",
            "README" to "README (1)",
            "archive.tar.gz" to "archive.tar (1).gz",
            ".env" to ".env (1)",
            ".config.json" to ".config (1).json",
            "name." to "name (1).",
            "中文 😀 ' \n.txt" to "中文 😀 ' \n (1).txt",
        )
        cases.forEach { (original, expected) ->
            assertEquals(original, resolver.resolve(original, 0).getOrThrow().value)
            assertEquals(expected, resolver.resolve(original, 1).getOrThrow().value)
        }
    }

    @Test fun `invalid originals attempts and generated byte overflow are typed failures`() {
        listOf("", " ", ".", "..", "a/b", "a\u0000b").forEach {
            assertTrue(resolver.resolve(it, 0).exceptionOrNull() is TargetNameException.InvalidName)
        }
        assertTrue(resolver.resolve("a", -1).exceptionOrNull() is TargetNameException.InvalidAttempt)
        assertTrue(resolver.resolve("a", 100).exceptionOrNull() is TargetNameException.AttemptsExhausted)
        val name = "你".repeat(83) + ".txt"
        assertTrue(resolver.resolve(name, 1).exceptionOrNull() is TargetNameException.NameTooLong)
    }

    @Test fun `rejects malformed unicode surrogates but preserves a valid emoji pair`() {
        assertTrue(resolver.resolve("bad-\uD83D.txt", 0).exceptionOrNull() is TargetNameException.InvalidName)
        assertTrue(resolver.resolve("bad-\uDE00.txt", 0).exceptionOrNull() is TargetNameException.InvalidName)
        assertEquals("ok-😀 (1).txt", resolver.resolve("ok-😀.txt", 1).getOrThrow().value)
    }
}
